// apps/web/src/routes/forgot-password/+page.svelte
<script lang="ts">
  import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-svelte";
  import { api } from "$lib/api";

  let email = $state("");
  let loading = $state(false);
  let error = $state<string | null>(null);
  let sent = $state(false);

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    error = null;
    loading = true;

    try {
      const response = await api.api.v1.auth.password.forgot.$post({
        json: { email: email.trim() },
      });
      if (!response.ok) {
        const body = await response.json().catch(() => null);
        throw new Error((body as any)?.error?.message ?? "Gagal mengirim tautan reset password.");
      }
      sent = true;
    } catch (err) {
      error = err instanceof Error ? err.message : "Gagal mengirim tautan reset password.";
    } finally {
      loading = false;
    }
  }
</script>

<svelte:head>
  <title>Lupa Password — SIMTAS FILKOM</title>
  <meta name="description" content="Minta tautan untuk mengatur ulang password akun SIMTAS FILKOM." />
</svelte:head>

<div class="flex min-h-screen items-center justify-center bg-background px-6 py-10 sm:px-10">
  <main id="main-content" class="w-full max-w-sm">
    <a href="/login" class="mb-8 inline-flex items-center gap-1.5 text-sm text-muted-foreground transition hover:text-foreground">
      <ArrowLeft class="h-4 w-4" aria-hidden="true" /> Kembali ke login
    </a>

    <div class="mb-8">
      <span class="landing-eyebrow">Pemulihan Akun</span>
      <h1 class="landing-heading mt-3 text-3xl md:text-4xl">Atur ulang password.</h1>
      <p class="mt-2 text-sm text-muted-foreground">
        Masukkan email akun Anda. Jika terdaftar, tautan reset akan dikirim ke email tersebut.
      </p>
    </div>

    {#if sent}
      <div role="status" aria-live="polite" class="rounded-2xl border border-primary/30 bg-primary-50 p-5 text-sm text-foreground">
        <div class="flex items-start gap-3">
          <CheckCircle2 class="mt-0.5 h-5 w-5 shrink-0 text-primary" aria-hidden="true" />
          <div>
            <p class="font-medium">Permintaan berhasil diproses.</p>
            <p class="mt-1 text-muted-foreground">
              Periksa inbox email Anda untuk melanjutkan. Jika email terdaftar, tautan reset akan tersedia selama satu jam.
            </p>
          </div>
        </div>
        <a href="/login" class="mt-5 inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline">
          Kembali ke login <ArrowRight class="h-4 w-4" aria-hidden="true" />
        </a>
      </div>
    {:else}
      {#if error}
        <div id="forgot-password-error" role="alert" aria-live="assertive" class="mb-4 rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
          {error}
        </div>
      {/if}

      <form onsubmit={handleSubmit} class="space-y-4">
        <div>
          <label for="email" class="mb-1.5 block text-sm font-medium text-foreground">Email</label>
          <input
            id="email"
            type="email"
            bind:value={email}
            placeholder="nama@unida.ac.id"
            autocomplete="email"
            required
            aria-invalid={error ? "true" : undefined}
            aria-describedby={error ? "forgot-password-error" : undefined}
            class="w-full rounded-md border border-border bg-background px-3 py-2.5 text-base text-foreground outline-none transition focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring sm:text-sm"
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          aria-busy={loading}
          class="flex w-full items-center justify-center gap-1.5 rounded-md bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground transition hover:bg-primary-700 disabled:cursor-wait disabled:opacity-60"
        >
          {loading ? "Mengirim tautan…" : "Kirim tautan reset"}
          <ArrowRight class="h-4 w-4" aria-hidden="true" />
        </button>
      </form>
    {/if}
  </main>
</div>

// frontend/src/app/(auth)/forgot-password/page.tsx
'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { ArrowLeft } from 'lucide-react'
import { Alert } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useForgotPasswordMutation } from '@/lib/hooks/use-auth'
import { getErrorMessage } from '@/lib/utils/error'

const forgotSchema = z.object({
  email: z.string().min(1, 'Email wajib diisi').email('Format email tidak valid'),
})

type ForgotForm = z.infer<typeof forgotSchema>

export default function ForgotPasswordPage() {
  const [error, setError] = useState<string | null>(null)
  const [done, setDone] = useState(false)
  const forgot = useForgotPasswordMutation()
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<ForgotForm>({ resolver: zodResolver(forgotSchema) })

  const onSubmit = handleSubmit(async (data) => {
    setError(null)
    try {
      await forgot.mutateAsync(data)
      setDone(true)
    } catch (err) {
      setError(getErrorMessage(err, 'Gagal mengirim email reset. Silakan coba lagi.'))
    }
  })

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4 py-10">
      <div className="w-full max-w-md">
        <div className="st-card rounded-2xl p-8">
          <div className="mb-6 text-center">
            <span className="font-mono text-[0.7rem] uppercase tracking-[0.25em] text-muted-foreground">
              Lupa Password
            </span>
            <h1 className="landing-display mt-3 text-3xl">Atur ulang password</h1>
            <p className="mt-2 text-sm text-muted-foreground">
              Masukkan email terdaftar Anda, kami akan mengirimkan tautan untuk mereset password.
            </p>
          </div>

          {done ? (
            <div className="space-y-4 text-center">
              <Alert variant="success">
                Jika email terdaftar, tautan reset password telah dikirim. Periksa kotak masuk Anda.
              </Alert>
              <Button asChild variant="outline" className="w-full">
                <Link href="/login">Kembali ke Login</Link>
              </Button>
            </div>
          ) : (
            <form onSubmit={onSubmit} noValidate className="space-y-4">
              {error && <Alert variant="danger">{error}</Alert>}
              <div>
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="nama@unida.ac.id"
                  invalid={!!errors.email}
                  {...register('email')}
                />
                {errors.email && <p className="mt-1 text-xs text-danger-700">{errors.email.message}</p>}
              </div>
              <Button type="submit" fullWidth loading={forgot.isPending}>
                Kirim Tautan Reset
              </Button>
              <p className="text-center text-sm">
                <Link href="/login" className="inline-flex items-center gap-1.5 font-medium text-primary hover:underline">
                  <ArrowLeft className="h-3.5 w-3.5" /> Kembali ke Login
                </Link>
              </p>
            </form>
          )}
        </div>
      </div>
    </div>
  )
}
