// frontend/src/app/(dashboard)/documents/page.tsx
'use client'

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Download, FileText, Upload, CheckCircle2, RefreshCcw, Eye, Loader2, X } from 'lucide-react'
import { useRef, useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'
import { Spinner } from '@/components/ui/spinner'
import { documentApi } from '@/lib/api/document-api'
import { documentTypeLabel, DOCUMENT_STATUS_LABELS, type DocumentType } from '@/types/document'
import { formatDate } from '@/lib/utils/date'
import { getErrorMessage } from '@/lib/utils/error'
import { useAuthStore } from '@/lib/stores/auth-store'
import { useThesisPicker } from '@/lib/hooks/use-thesis-picker'

// Document types match backend constants (Job 07/21).
const TYPES: { value: DocumentType; label: string }[] = [
  { value: 'proposal', label: 'Proposal' },
  { value: 'draft_chapter', label: 'Draft Bab' },
  { value: 'seminar_doc', label: 'Dokumen Seminar' },
  { value: 'defense_doc', label: 'Dokumen Sidang' },
  { value: 'final_thesis', label: 'Skripsi Final' },
  { value: 'revision_sheet', label: 'Lembar Revisi' },
  { value: 'endorsement_letter', label: 'Surat Pengesahan' },
]

function statusBadge(status: string) {
  switch (status) {
    case 'approved':
      return <Badge variant="success"><CheckCircle2 className="h-3 w-3" /> {DOCUMENT_STATUS_LABELS.approved}</Badge>
    case 'revision_required':
      return <Badge variant="danger"><RefreshCcw className="h-3 w-3" /> {DOCUMENT_STATUS_LABELS.revision_required}</Badge>
    default:
      return <Badge variant="warning">{DOCUMENT_STATUS_LABELS.pending_review}</Badge>
  }
}

export default function DocumentsPage() {
  const { user } = useAuthStore()
  const queryClient = useQueryClient()
  const isStudent = user?.role === 'mahasiswa'
  const [selectedType, setSelectedType] = useState('')
  const [uploadType, setUploadType] = useState<DocumentType>('proposal')
  const [chapterNumber, setChapterNumber] = useState('1')
  const [uploading, setUploading] = useState(false)
  const [uploadProgress, setUploadProgress] = useState(0)
  const uploadAbortRef = useRef<AbortController | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [downloadingId, setDownloadingId] = useState<string | null>(null)

  const { thesis: myThesis, picker, isLoading: thesesLoading } = useThesisPicker()

  const docs = useQuery({
    queryKey: ['documents', myThesis?.id, selectedType],
    queryFn: () =>
      myThesis?.id
        ? documentApi.list(myThesis.id, { per_page: 50, document_type: selectedType || undefined })
        : Promise.resolve(null),
    enabled: Boolean(myThesis?.id),
  })

  const review = useMutation({
    mutationFn: ({ id, decision, notes }: { id: string; decision: 'approved' | 'revision_required'; notes?: string }) =>
      documentApi.review(id, decision, notes),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['documents'] })
    },
    onError: (e) => setError(getErrorMessage(e)),
  })

  const list = docs.data?.data ?? []

  async function handleUpload(file: File) {
    if (!myThesis?.id) return
    setError(null)
    setUploading(true)
    setUploadProgress(0)
    const controller = new AbortController()
    uploadAbortRef.current = controller
    try {
      await documentApi.upload(
        myThesis.id,
        file,
        uploadType,
        uploadType === 'draft_chapter' ? Number(chapterNumber) : undefined,
        setUploadProgress,
        controller.signal,
      )
      queryClient.invalidateQueries({ queryKey: ['documents'] })
    } catch (e) {
      if (!controller.signal.aborted) {
        setError(getErrorMessage(e))
      }
    } finally {
      uploadAbortRef.current = null
      setUploading(false)
      setUploadProgress(0)
    }
  }

  function cancelUpload() {
    uploadAbortRef.current?.abort()
  }

  async function handleDownload(thesisId: string, id: string) {
    setDownloadingId(id)
    setError(null)
    try {
      await documentApi.download(thesisId, id)
    } catch (e) {
      setError(getErrorMessage(e))
    } finally {
      setDownloadingId(null)
    }
  }

  if (thesesLoading) return <Spinner label="Memuat dokumen…" />

  if (!myThesis) {
    return (
      <Card>
        <CardContent className="py-14 text-center">
          <FileText className="mx-auto h-10 w-10 text-muted-foreground" />
          <p className="mt-4 font-semibold">Belum ada skripsi aktif</p>
          <p className="mt-1 text-sm text-muted-foreground">Ajukan skripsi terlebih dahulu untuk mengunggah dokumen.</p>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">Dokumen</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            {isStudent ? 'Unggah dan pantau dokumen skripsi Anda' : 'Review dokumen yang diunggah mahasiswa bimbingan'}
          </p>
          {!isStudent && picker}
        </div>
        {isStudent && (
          <div className="flex flex-wrap items-end gap-2">
            <div>
              <Label htmlFor="type">Jenis Dokumen</Label>
              <Select id="type" value={uploadType} onChange={(e) => setUploadType(e.target.value as DocumentType)} className="w-44">
                {TYPES.map((t) => (
                  <option key={t.value} value={t.value}>{t.label}</option>
                ))}
              </Select>
            </div>
            {uploadType === 'draft_chapter' && (
              <div>
                <Label htmlFor="chapter">Bab</Label>
                <Select id="chapter" value={chapterNumber} onChange={(e) => setChapterNumber(e.target.value)} className="w-20">
                  {['1', '2', '3', '4', '5'].map((n) => (
                    <option key={n} value={n}>{n}</option>
                  ))}
                </Select>
              </div>
            )}
            {uploading ? (
              <Button size="sm" variant="ghost" onClick={cancelUpload}>
                <X className="h-4 w-4" /> Batalkan
              </Button>
            ) : (
              <label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary-700">
                <Upload className="h-4 w-4" />
                Unggah
                <input
                  type="file"
                  accept=".pdf"
                  className="hidden"
                  onChange={(e) => {
                    const f = e.target.files?.[0]
                    if (f) handleUpload(f)
                    e.target.value = ''
                  }}
                />
              </label>
            )}
          </div>
        )}
      </div>

      {uploading && (
        <div className="space-y-1">
          <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
            <div
              className="h-full rounded-full bg-primary transition-all duration-300"
              style={{ width: `${uploadProgress}%` }}
            />
          </div>
          <p className="text-xs text-muted-foreground">{uploadProgress}% terunggah</p>
        </div>
      )}

      {error && <p className="text-sm text-danger">{error}</p>}

      <div className="flex flex-wrap gap-2">
        <Button
          size="sm"
          variant={selectedType === '' ? 'primary' : 'outline'}
          onClick={() => setSelectedType('')}
        >
          Semua
        </Button>
        {TYPES.map((t) => (
          <Button
            key={t.value}
            size="sm"
            variant={selectedType === t.value ? 'primary' : 'outline'}
            onClick={() => setSelectedType(t.value)}
          >
            {t.label}
          </Button>
        ))}
      </div>

      <div className="space-y-3">
        {docs.isLoading && <Spinner />}
        {list.map((doc) => (
          <Card key={doc.id}>
            <CardContent className="flex flex-wrap items-center justify-between gap-3 p-4">
              <div className="flex min-w-0 items-center gap-3">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary-50 text-primary">
                  <FileText className="h-5 w-5" />
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <p className="truncate font-medium">{doc.file_name}</p>
                    {statusBadge(doc.status)}
                  </div>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    {documentTypeLabel(doc.document_type)}
                    {doc.chapter_number ? ` Bab ${doc.chapter_number}` : ''} · v{doc.version}
                    {doc.file_size != null && ` · ${(doc.file_size / 1024 / 1024).toFixed(2)} MB`} · {formatDate(doc.created_at)}
                  </p>
                  {doc.reviewer_notes && doc.status === 'revision_required' && (
                    <p className="mt-1 text-xs text-danger-700">Catatan revisi: {doc.reviewer_notes}</p>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  size="sm"
                  variant="outline"
                  disabled={downloadingId === doc.id}
                  onClick={() => handleDownload(myThesis.id, doc.id)}
                >
                  {downloadingId === doc.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
                  Unduh
                </Button>
                {!isStudent && doc.status === 'pending_review' && (
                  <>
                    <Button
                      size="sm"
                      variant="success"
                      onClick={() => review.mutate({ id: doc.id, decision: 'approved' })}
                    >
                      <CheckCircle2 className="h-3.5 w-3.5" /> Setujui
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => review.mutate({ id: doc.id, decision: 'revision_required', notes: 'Silakan perbaiki sesuai catatan.' })}
                    >
                      <RefreshCcw className="h-3.5 w-3.5" /> Minta Revisi
                    </Button>
                  </>
                )}
                {!isStudent && doc.status !== 'pending_review' && (
                  <Button
                    size="sm"
                    variant="ghost"
                    disabled={downloadingId === doc.id}
                    onClick={() => handleDownload(myThesis.id, doc.id)}
                  >
                    <Eye className="h-3.5 w-3.5" /> Lihat
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
        {!docs.isLoading && list.length === 0 && (
          <p className="py-10 text-center text-sm text-muted-foreground">Belum ada dokumen.</p>
        )}
      </div>
    </div>
  )
}

// apps/web/src/routes/dashboard/documents/+page.svelte
<script lang="ts">
  import { FileText, Download, CheckCircle2, RefreshCcw, Eye, Loader2 } from "lucide-svelte";
  import { api } from "$lib/api";
  import { auth } from "$lib/auth.store";
  import StatusBadge from "$lib/components/dashboard/StatusBadge.svelte";
  import Reveal from "$lib/components/landing/Reveal.svelte";
  import type { StatusVariant } from "$lib/components/dashboard/thesis-status";

  const DOCUMENT_TYPES: { value: string; label: string }[] = [
    { value: "proposal", label: "Proposal" },
    { value: "draft_chapter", label: "Draft Bab" },
    { value: "seminar_doc", label: "Dokumen Seminar" },
    { value: "defense_doc", label: "Dokumen Sidang" },
    { value: "final_thesis", label: "Skripsi Final" },
    { value: "revision_sheet", label: "Lembar Revisi" },
    { value: "endorsement_letter", label: "Surat Pengesahan" },
  ];

  const TYPE_LABEL: Record<string, string> = Object.fromEntries(
    DOCUMENT_TYPES.map((t) => [t.value, t.label]),
  );

  const STATUS_LABEL: Record<string, string> = {
    pending_review: "Menunggu Review",
    approved: "Disetujui",
    revision_required: "Perlu Revisi",
  };

  const STATUS_VARIANT: Record<string, StatusVariant> = {
    pending_review: "pending",
    approved: "approved",
    revision_required: "rejected",
  };

  const isStudent = $derived(($auth.user as any)?.role === "mahasiswa");

  let theses = $state<any[]>([]);
  let thesesLoading = $state(true);
  let selectedThesisId = $state<string | null>(null);

  let list = $state<any[]>([]);
  let loading = $state(true);
  let error = $state("");
  let actionError = $state("");
  let downloadingId = $state<string | null>(null);

  let selectedType = $state("");

  const activeThesis = $derived(
    isStudent ? theses[0] : theses.find((t) => t.id === selectedThesisId) ?? theses[0],
  );
  const activeThesisId = $derived(activeThesis?.id as string | undefined);

  async function loadTheses() {
    thesesLoading = true;
    try {
      const res = await api.api.v1.theses.$get({ query: { per_page: "100" } });
      const json: any = res.ok ? await res.json() : null;
      theses = json?.data ?? json ?? [];
    } catch {
      theses = [];
    } finally {
      thesesLoading = false;
    }
  }

  async function loadDocuments() {
    if (!activeThesisId) {
      list = [];
      loading = false;
      return;
    }
    loading = true;
    error = "";
    try {
      const query: Record<string, string> = { thesisId: activeThesisId, per_page: "50" };
      if (selectedType) query.document_type = selectedType;
      const res = await api.api.v1.documents.$get({ query });
      const json: any = res.ok ? await res.json() : null;
      list = json?.data ?? [];
    } catch {
      error = "Gagal memuat daftar dokumen.";
    } finally {
      loading = false;
    }
  }

  $effect(() => {
    loadTheses();
  });

  $effect(() => {
    activeThesisId; selectedType;
    loadDocuments();
  });

  async function downloadDoc(id: string) {
    if (!activeThesisId) return;
    downloadingId = id;
    actionError = "";
    try {
      const res = await api.api.v1.documents[":id"].download.$get({
        param: { id },
        query: { thesisId: activeThesisId },
      });
      const json: any = res.ok ? await res.json() : null;
      const url = json?.data?.url ?? json?.url;
      if (url) {
        window.open(url, "_blank", "noopener");
      } else {
        actionError = "URL unduhan tidak tersedia.";
      }
    } catch {
      actionError = "Gagal mengunduh dokumen.";
    } finally {
      downloadingId = null;
    }
  }

  async function reviewDoc(id: string, decision: "approved" | "revision_required") {
    actionError = "";
    try {
      const res = await api.api.v1.documents[":id"].review.$patch({
        param: { id },
        json: { decision, notes: decision === "revision_required" ? "Silakan perbaiki sesuai catatan." : undefined },
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        actionError = (body as any)?.error?.message ?? "Gagal memperbarui status dokumen.";
        return;
      }
      await loadDocuments();
    } catch {
      actionError = "Gagal memperbarui status dokumen.";
    }
  }

  function statusBadge(status?: string) {
    const key = status ?? "pending_review";
    return {
      variant: STATUS_VARIANT[key] ?? "draft",
      label: STATUS_LABEL[key] ?? key.replace(/_/g, " "),
    };
  }

  function formatDate(s?: string) {
    if (!s) return "—";
    try {
      return new Date(s).toLocaleDateString("id-ID", { day: "2-digit", month: "short", year: "numeric" });
    } catch {
      return s;
    }
  }

  function formatSize(bytes?: number | null) {
    if (bytes == null) return null;
    return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
  }
</script>

<div class="space-y-6">
  <Reveal>
    <div class="flex flex-wrap items-end justify-between gap-3">
      <div>
        <p class="landing-eyebrow">Dokumen Skripsi</p>
        <h1 class="mt-2 text-balance landing-heading text-2xl">
          {#if isStudent}
            Unggah dan Pantau <span class="accent-text italic">Dokumen</span>
          {:else}
            Review Dokumen <span class="accent-text italic">Mahasiswa</span>
          {/if}
        </h1>
        <p class="mt-1.5 text-sm text-st-muted">
          {isStudent
            ? "Unggah dan pantau dokumen skripsi Anda"
            : "Review dokumen yang diunggah mahasiswa bimbingan"}
        </p>
        {#if !isStudent}
          {#if thesesLoading}
            <p class="mt-2 text-xs text-st-muted">Memuat daftar skripsi…</p>
          {:else if theses.length > 1}
            <div class="mt-3">
              <label for="thesis-picker" class="sr-only">Pilih skripsi mahasiswa</label>
              <select
                id="thesis-picker"
                value={activeThesisId ?? ""}
                onchange={(e) => (selectedThesisId = (e.currentTarget as HTMLSelectElement).value || null)}
                class="max-w-xs rounded-md border border-st-stroke bg-st-surface px-3 py-2 text-sm text-st-text outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring"
              >
                {#each theses as t (t.id)}
                  <option value={t.id}>
                    {(t.student?.fullName ?? t.student?.full_name ?? "—") + " — " + (t.title ?? "").slice(0, 40)}{(t.title?.length ?? 0) > 40 ? "…" : ""}
                  </option>
                {/each}
              </select>
            </div>
          {/if}
        {/if}
      </div>
    </div>
  </Reveal>

  {#if error}
    <div role="alert" class="rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
      {error}
    </div>
  {/if}
  {#if actionError}
    <div role="alert" class="rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
      {actionError}
    </div>
  {/if}

  {#if thesesLoading}
    <div class="py-10 text-center text-sm text-st-muted">Memuat dokumen…</div>
  {:else if !activeThesisId}
    <div class="rounded-2xl border border-st-stroke bg-st-surface py-14 text-center">
      <FileText size={40} class="mx-auto text-st-muted" aria-hidden="true" />
      <p class="mt-4 font-semibold text-st-text">Belum ada skripsi aktif</p>
      <p class="mt-1 text-sm text-st-muted">
        {isStudent
          ? "Ajukan skripsi terlebih dahulu untuk mengelola dokumen."
          : "Pilih skripsi mahasiswa untuk melihat dokumennya."}
      </p>
    </div>
  {:else}
    <div class="flex flex-wrap gap-2">
      <button
        type="button"
        onclick={() => (selectedType = "")}
        class="inline-flex h-8 items-center rounded-md border px-3 text-sm font-medium transition-colors {selectedType === '' ? 'border-primary bg-primary text-primary-foreground' : 'border-st-stroke bg-st-surface text-st-text hover:bg-st-surface-hi'}"
      >
        Semua
      </button>
      {#each DOCUMENT_TYPES as t (t.value)}
        <button
          type="button"
          onclick={() => (selectedType = t.value)}
          class="inline-flex h-8 items-center rounded-md border px-3 text-sm font-medium transition-colors {selectedType === t.value ? 'border-primary bg-primary text-primary-foreground' : 'border-st-stroke bg-st-surface text-st-text hover:bg-st-surface-hi'}"
        >
          {t.label}
        </button>
      {/each}
    </div>

    {#if loading}
      <div class="py-10 text-center text-sm text-st-muted">Memuat dokumen…</div>
    {:else}
      <div class="space-y-3">
        {#each list as doc (doc.id)}
          {@const sb = statusBadge(doc.status)}
          {@const typeLabel = TYPE_LABEL[doc.document_type] ?? doc.document_type}
          {@const size = formatSize(doc.file_size ?? doc.fileSize)}
          <article class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-st-stroke bg-st-surface p-5">
            <div class="flex min-w-0 items-center gap-3">
              <div class="accent-ring flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-(--st-accent-from)/10 text-(--st-accent-to)">
                <FileText size={20} aria-hidden="true" />
              </div>
              <div class="min-w-0">
                <div class="flex flex-wrap items-center gap-2">
                  <p class="truncate font-medium text-st-text">{doc.file_name ?? doc.fileName ?? "—"}</p>
                  <StatusBadge variant={sb.variant} label={sb.label} />
                </div>
                <p class="mt-0.5 text-xs text-st-muted">
                  {typeLabel}{doc.chapter_number ? ` · Bab ${doc.chapter_number}` : ""}{doc.version != null ? ` · v${doc.version}` : ""}{size ? ` · ${size}` : ""} · {formatDate(doc.created_at ?? doc.createdAt)}
                </p>
                {#if doc.reviewer_notes && doc.status === "revision_required"}
                  <p class="mt-1 text-xs text-danger-700">Catatan revisi: {doc.reviewer_notes}</p>
                {/if}
              </div>
            </div>
            <div class="flex flex-wrap items-center gap-2">
              <button
                type="button"
                disabled={downloadingId === doc.id}
                onclick={() => downloadDoc(doc.id)}
                class="inline-flex h-8 items-center gap-1.5 rounded-md border border-st-stroke bg-st-surface px-3 text-sm font-medium text-st-text hover:bg-st-surface-hi disabled:opacity-50"
              >
                {#if downloadingId === doc.id}
                  <Loader2 size={14} aria-hidden="true" class="animate-spin" />
                {:else}
                  <Download size={14} aria-hidden="true" />
                {/if}
                Unduh
              </button>
              {#if !isStudent && doc.status === "pending_review"}
                <button
                  type="button"
                  onclick={() => reviewDoc(doc.id, "approved")}
                  class="inline-flex h-8 items-center gap-1.5 rounded-md bg-success px-3 text-sm font-medium text-white hover:bg-success/90"
                >
                  <CheckCircle2 size={14} aria-hidden="true" /> Setujui
                </button>
                <button
                  type="button"
                  onclick={() => reviewDoc(doc.id, "revision_required")}
                  class="inline-flex h-8 items-center gap-1.5 rounded-md border border-st-stroke bg-st-surface px-3 text-sm font-medium text-st-text hover:bg-st-surface-hi"
                >
                  <RefreshCcw size={14} aria-hidden="true" /> Minta Revisi
                </button>
              {:else if !isStudent}
                <button
                  type="button"
                  disabled={downloadingId === doc.id}
                  onclick={() => downloadDoc(doc.id)}
                  class="inline-flex h-8 items-center gap-1.5 rounded-md border border-st-stroke bg-st-surface px-3 text-sm font-medium text-st-text hover:bg-st-surface-hi disabled:opacity-50"
                >
                  <Eye size={14} aria-hidden="true" /> Lihat
                </button>
              {/if}
            </div>
          </article>
        {/each}
        {#if list.length === 0}
          <div class="rounded-2xl border border-st-stroke bg-st-surface py-12 text-center">
            <FileText size={36} class="mx-auto text-st-muted" aria-hidden="true" />
            <p class="mt-3 landing-heading text-lg">Belum ada <span class="accent-text italic">dokumen</span></p>
            <p class="mt-1 text-sm text-st-muted">
              {isStudent
                ? "Unggah dokumen skripsi pertama Anda untuk memulai."
                : "Mahasiswa belum mengunggah dokumen untuk skripsi ini."}
            </p>
          </div>
        {/if}
      </div>
    {/if}
  {/if}
</div>
