// apps/web/src/routes/dashboard/admin/audit-logs/+page.svelte
<script lang="ts">
  import { ShieldCheck } from "lucide-svelte";
  import { api } from "$lib/api";

  let action = $state("");
  let page = $state(1);
  const perPage = 25;

  let list = $state<any[]>([]);
  let total = $state(0);
  let loading = $state(true);
  let error = $state("");

  const actionOptions: { value: string; label: string }[] = [
    { value: "", label: "Semua aksi" },
    { value: "USER_LOGIN", label: "Login" },
    { value: "USER_LOGOUT", label: "Logout" },
    { value: "USER_CREATED", label: "User dibuat" },
    { value: "THESIS_SUBMITTED", label: "Skripsi diajukan" },
    { value: "THESIS_REVIEWED", label: "Skripsi direview" },
    { value: "DOCUMENT_UPLOADED", label: "Dokumen diunggah" },
    { value: "SEMINAR_SCHEDULED", label: "Seminar dijadwalkan" },
    { value: "DEFENSE_SCHEDULED", label: "Sidang dijadwalkan" },
    { value: "THESIS_GRADUATED", label: "Wisuda" },
  ];

  async function load() {
    loading = true;
    error = "";
    try {
      const query: Record<string, string> = { page: String(page), per_page: String(perPage) };
      if (action) query.action = action;
      const res = await api.api.v1.auditLogs.$get({ query });
      const json: any = res.ok ? await res.json() : null;
      list = json?.data ?? [];
      total = json?.meta?.total ?? 0;
    } catch (e) {
      error = "Gagal memuat audit log.";
    } finally {
      loading = false;
    }
  }

  $effect(() => {
    action; page;
    load();
  });

  function formatDateTime(s?: string) {
    if (!s) return "—";
    try {
      return new Date(s).toLocaleString("id-ID", {
        day: "2-digit",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      });
    } catch {
      return s;
    }
  }
</script>

<div class="space-y-6">
  <div>
    <p class="landing-eyebrow">Audit Log</p>
    <h1 class="mt-2 text-balance landing-heading text-2xl">
      Jejak aktivitas seluruh <span class="accent-text italic">pengguna</span> sistem
    </h1>
  </div>

  <div class="flex flex-wrap items-center gap-3">
    <select
      bind:value={action}
      onchange={() => (page = 1)}
      class="w-56 rounded-md border border-st-stroke bg-st-surface px-3 py-2 text-sm text-st-text outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring"
    >
      {#each actionOptions as opt}
        <option value={opt.value}>{opt.label}</option>
      {/each}
    </select>
  </div>

  {#if error}
    <div role="alert" class="rounded-2xl border border-danger-700/40 bg-danger-50 px-4 py-3 text-sm text-danger-700">
      {error}
    </div>
  {/if}

  {#if loading}
    <div class="rounded-2xl border border-st-stroke bg-st-surface py-10 text-center text-sm text-st-muted">
      Memuat audit log…
    </div>
  {:else}
    <div class="overflow-x-auto rounded-2xl border border-st-stroke bg-st-surface">
      <table class="w-full text-left text-sm">
        <thead class="border-b border-st-stroke text-xs uppercase tracking-[0.15em] text-st-muted">
          <tr>
            <th class="px-4 py-3 font-medium">Waktu</th>
            <th class="px-4 py-3 font-medium">Pengguna</th>
            <th class="px-4 py-3 font-medium">Aksi</th>
            <th class="px-4 py-3 font-medium">Entitas</th>
            <th class="px-4 py-3 font-medium">IP</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-st-stroke">
          {#each list as l (l.id)}
            <tr class="text-st-text">
              <td class="whitespace-nowrap px-4 py-3 font-mono text-xs text-st-muted">
                {formatDateTime(l.created_at ?? l.createdAt)}
              </td>
              <td class="px-4 py-3">
                {l.user?.full_name ?? l.user?.fullName ?? "—"}
              </td>
              <td class="px-4 py-3">
                <span class="inline-flex items-center rounded-md bg-st-surface-hi px-2 py-0.5 font-mono text-xs text-st-text">
                  {l.action}
                </span>
              </td>
              <td class="px-4 py-3 text-xs text-st-muted">
                {l.entity_type ?? l.entityType ?? "—"}
                {#if l.entity_id ?? l.entityId}
                  · {(l.entity_id ?? l.entityId).slice(0, 8)}…
                {/if}
              </td>
              <td class="px-4 py-3 font-mono text-xs text-st-muted">
                {l.ip_address ?? l.ipAddress ?? "—"}
              </td>
            </tr>
          {/each}
          {#if list.length === 0}
            <tr>
              <td colspan="5" class="px-4 py-12 text-center">
                <ShieldCheck size={36} class="mx-auto text-st-muted" />
                <p class="mt-3 landing-heading text-lg">
                  Belum ada <span class="accent-text italic">log</span> aktivitas
                </p>
                <p class="mt-1 text-sm text-st-muted">
                  Aktivitas sistem akan tercatat di sini secara otomatis.
                </p>
              </td>
            </tr>
          {/if}
        </tbody>
      </table>
    </div>

    {#if total > perPage}
      <div class="flex items-center justify-between pt-2">
        <p class="text-sm text-st-muted">Total {total} log · Halaman {page}</p>
        <div class="flex gap-2">
          <button
            type="button"
            disabled={page <= 1}
            onclick={() => (page -= 1)}
            class="inline-flex h-8 items-center rounded-md border border-st-stroke bg-st-surface px-3 text-sm text-st-text hover:bg-st-surface-hi disabled:opacity-50"
          >
            Sebelumnya
          </button>
          <button
            type="button"
            disabled={page >= Math.ceil(total / perPage)}
            onclick={() => (page += 1)}
            class="inline-flex h-8 items-center rounded-md border border-st-stroke bg-st-surface px-3 text-sm text-st-text hover:bg-st-surface-hi disabled:opacity-50"
          >
            Berikutnya
          </button>
        </div>
      </div>
    {/if}
  {/if}
</div>

// frontend/src/app/(dashboard)/admin/audit-logs/page.tsx
'use client'

import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Select } from '@/components/ui/select'
import { ListSkeleton } from '@/components/ui/skeleton'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import apiClient from '@/lib/api/client'
import { formatDateTime } from '@/lib/utils/date'
import type { PaginatedResponse } from '@/types/api'

interface AuditLog {
  id: string
  user_id?: string
  user?: { full_name: string; email: string } | null
  action: string
  entity_type?: string
  entity_id?: string
  ip_address?: string
  user_agent?: string
  created_at: string
}

export default function AuditLogsPage() {
  const [action, setAction] = useState('')
  const [page, setPage] = useState(1)

  const logs = useQuery({
    queryKey: ['admin', 'audit-logs', action, page],
    queryFn: async () => {
      const res = await apiClient.get<PaginatedResponse<AuditLog>>('/admin/audit-logs', {
        params: { action: action || undefined, page, per_page: 25 },
      })
      return res.data
    },
  })

  const list = logs.data?.data ?? []
  const total = logs.data?.meta.total ?? 0

  return (
    <div className="space-y-6">
      <div>
        <p className="landing-eyebrow">Audit Log</p>
        <h1 className="mt-2 text-balance landing-heading text-2xl">
          Jejak aktivitas seluruh <span className="accent-text italic">pengguna</span> sistem
        </h1>
      </div>

      <div className="flex flex-wrap items-center gap-3">
        <Select value={action} onChange={(e) => { setAction(e.target.value); setPage(1) }} className="w-56">
          <option value="">Semua aksi</option>
          <option value="USER_LOGIN">Login</option>
          <option value="USER_LOGOUT">Logout</option>
          <option value="USER_CREATED">User dibuat</option>
          <option value="THESIS_SUBMITTED">Skripsi diajukan</option>
          <option value="THESIS_REVIEWED">Skripsi direview</option>
          <option value="DOCUMENT_UPLOADED">Dokumen diunggah</option>
          <option value="SEMINAR_SCHEDULED">Seminar dijadwalkan</option>
          <option value="DEFENSE_SCHEDULED">Sidang dijadwalkan</option>
          <option value="THESIS_GRADUATED">Wisuda</option>
        </Select>
      </div>

      {logs.isLoading ? (
        <ListSkeleton count={6} label="Memuat audit log…" />
      ) : (
        <>
          {/* Desktop table */}
          <div className="hidden md:block overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Waktu</TableHead>
                  <TableHead>Pengguna</TableHead>
                  <TableHead>Aksi</TableHead>
                  <TableHead>Entitas</TableHead>
                  <TableHead>IP</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {list.map((l) => (
                  <TableRow key={l.id}>
                    <TableCell className="whitespace-nowrap text-xs">{formatDateTime(l.created_at)}</TableCell>
                    <TableCell>{l.user?.full_name ?? '—'}</TableCell>
                    <TableCell><Badge variant="muted" className="font-mono">{l.action}</Badge></TableCell>
                    <TableCell className="text-xs text-muted-foreground">
                      {l.entity_type ?? '—'}
                      {l.entity_id ? ` · ${l.entity_id.slice(0, 8)}…` : ''}
                    </TableCell>
                    <TableCell className="text-xs text-muted-foreground">{l.ip_address ?? '—'}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          {/* Mobile cards */}
          <div className="space-y-3 md:hidden">
            {list.map((l) => (
              <Card key={l.id}>
                <CardContent className="p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="whitespace-nowrap text-xs text-muted-foreground">
                          {formatDateTime(l.created_at)}
                        </span>
                        <Badge variant="muted" className="font-mono text-[10px]">{l.action}</Badge>
                      </div>
                      <p className="mt-1.5 text-sm font-medium">{l.user?.full_name ?? '—'}</p>
                      <p className="mt-0.5 text-xs text-muted-foreground">
                        {l.entity_type ?? '—'}
                        {l.entity_id ? ` · ${l.entity_id.slice(0, 8)}…` : ''}
                      </p>
                    </div>
                    <span className="shrink-0 text-xs text-muted-foreground">{l.ip_address ?? '—'}</span>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {total > 25 && (
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">Total {total} log · Halaman {page}</p>
              <div className="flex gap-2">
                <Button size="sm" variant="outline" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Sebelumnya</Button>
                <Button size="sm" variant="outline" disabled={page >= Math.ceil(total / 25)} onClick={() => setPage((p) => p + 1)}>Berikutnya</Button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  )
}
