// apps/web/src/lib/components/ui/Pagination.svelte
<script lang="ts">
  let {
    total,
    page,
    pageSize,
    onPage,
  }: {
    total: number;
    page: number;
    pageSize: number;
    onPage: (next: number) => void;
  } = $props();

  const lastPage = $derived(Math.max(1, Math.ceil(total / pageSize)));
  const show = $derived(total > pageSize);
</script>

{#if show}
  <div class="flex flex-wrap items-center justify-between gap-3 pt-2">
    <p class="text-sm text-st-muted">Total {total} · Halaman {page}</p>
    <div class="flex gap-2">
      <button
        type="button"
        disabled={page <= 1}
        onclick={() => onPage(page - 1)}
        class="inline-flex h-9 items-center justify-center rounded-md border border-st-stroke bg-st-surface px-3 text-sm text-st-text transition-colors hover:bg-st-surface-hi disabled:opacity-50"
      >
        Sebelumnya
      </button>
      <button
        type="button"
        disabled={page >= lastPage}
        onclick={() => onPage(page + 1)}
        class="inline-flex h-9 items-center justify-center rounded-md border border-st-stroke bg-st-surface px-3 text-sm text-st-text transition-colors hover:bg-st-surface-hi disabled:opacity-50"
      >
        Berikutnya
      </button>
    </div>
  </div>
{/if}

// frontend/src/components/features/admin-users/pagination.tsx
import { Button } from '@/components/ui/button'

/** Kontrol pagination sederhana (sebelumnya / berikutnya). */
export function Pagination({
  page,
  total,
  perPage,
  onPageChange,
}: {
  page: number
  total: number
  perPage: number
  onPageChange: (page: number) => void
}) {
  if (total <= perPage) return null

  return (
    <div className="flex items-center justify-between">
      <p className="text-sm text-muted-foreground">Total {total} pengguna · Halaman {page}</p>
      <div className="flex gap-2">
        <Button size="sm" variant="outline" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Sebelumnya</Button>
        <Button size="sm" variant="outline" disabled={page >= Math.ceil(total / perPage)} onClick={() => onPageChange(page + 1)}>Berikutnya</Button>
      </div>
    </div>
  )
}
