// frontend/src/components/features/layout/sidebar.tsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { ChevronDown, LogOut, UserRound } from 'lucide-react'
import { useState } from 'react'
import { navItemsForRoles, APP_NAME } from '@/constants/navigation'
import { roleLabel } from '@/constants/roles'
import { cn } from '@/lib/utils/cn'
import { useLogoutMutation } from '@/lib/hooks/use-auth'
import { useAuthStore } from '@/lib/stores/auth-store'

function NavLink({ href, label, icon: Icon, onNavigate }: { href: string; label: string; icon: React.ElementType; onNavigate?: () => void }) {
  const pathname = usePathname()
  const active = pathname === href || (href !== '/dashboard' && pathname.startsWith(href))
  return (
    <Link
      href={href}
      onClick={onNavigate}
      className={cn(
        'flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors',
        active
          ? 'bg-primary/15 text-primary'
          : 'text-foreground/60 hover:bg-muted hover:text-foreground',
      )}
    >
      <Icon className="h-4.5 w-4.5 shrink-0" />
      {label}
    </Link>
  )
}

function BrandMark() {
  return (
    <span className="accent-ring relative flex h-8 w-8 items-center justify-center rounded-full">
      <span className="flex h-[calc(100%-3px)] w-[calc(100%-3px)] items-center justify-center rounded-full bg-background">
        <span className="font-display text-[13px] italic text-foreground">sf</span>
      </span>
    </span>
  )
}

export function Sidebar({ onNavigate }: { onNavigate?: () => void }) {
  const { user } = useAuthStore()
  const sections = navItemsForRoles(user ? [user.role] : [])

  return (
    <aside className="flex h-full w-64 flex-col border-r border-border bg-background">
      <div className="flex h-14 items-center gap-2.5 border-b border-border px-5">
        <BrandMark />
        <div className="leading-tight">
          <p className="text-sm font-semibold tracking-tight text-foreground">{APP_NAME}</p>
          <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">FILKOM · Unida</p>
        </div>
      </div>

      <nav className="flex-1 space-y-5 overflow-y-auto px-3 py-4">
        {sections.map((section, i) => (
          <div key={i}>
            {section.title && (
              <p className="mb-1.5 px-3 font-mono text-[10px] font-medium uppercase tracking-[0.2em] text-muted-foreground/60">
                {section.title}
              </p>
            )}
            <div className="space-y-0.5">
              {section.items.map((item) => (
                <NavLink key={item.href} href={item.href} label={item.label} icon={item.icon} onNavigate={onNavigate} />
              ))}
            </div>
          </div>
        ))}
      </nav>

      <div className="border-t border-border p-3">
        <Link
          href="/profile"
          onClick={onNavigate}
          className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-colors hover:bg-muted"
        >
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/15 text-xs font-bold text-primary">
            {(user?.full_name ?? '?').slice(0, 1).toUpperCase()}
          </div>
          <div className="min-w-0 flex-1 leading-tight">
            <p className="truncate text-sm font-medium text-foreground">{user?.full_name ?? 'User'}</p>
            <p className="truncate text-[11px] text-muted-foreground">{roleLabel(user?.role)}</p>
          </div>
          <ChevronDown className="h-4 w-4 text-muted-foreground" />
        </Link>
      </div>
    </aside>
  )
}

export function TopBar() {
  const { user } = useAuthStore()
  const logout = useLogoutMutation()
  const [menuOpen, setMenuOpen] = useState(false)

  return (
    <header className="flex h-14 items-center justify-between border-b border-border bg-background px-6">
      <div>
        <p className="text-sm font-medium text-foreground">Selamat datang,</p>
        <p className="font-mono text-[11px] uppercase tracking-[0.15em] text-muted-foreground">{roleLabel(user?.role)}</p>
      </div>

      <div className="relative">
        <button
          type="button"
          onClick={() => setMenuOpen((v) => !v)}
          className="flex items-center gap-2 rounded-lg px-3 py-1.5 text-sm font-medium text-foreground transition-colors hover:bg-muted"
        >
          <span className="h-2 w-2 rounded-full bg-success shadow-[0_0_8px] shadow-success/60" />
          <span className="hidden sm:inline">Menu</span>
        </button>
        {menuOpen && (
          <div
            className="absolute right-0 top-full z-50 mt-2 w-48 overflow-hidden rounded-xl border border-border bg-background shadow-xl"
            onMouseLeave={() => setMenuOpen(false)}
          >
            <Link
              href="/profile"
              className="flex items-center gap-2 px-4 py-2.5 text-sm text-foreground transition-colors hover:bg-muted"
              onClick={() => setMenuOpen(false)}
            >
              <UserRound className="h-4 w-4" /> Profil Saya
            </Link>
            <button
              type="button"
              onClick={() => {
                setMenuOpen(false)
                logout.mutate()
              }}
              className="flex w-full items-center gap-2 px-4 py-2.5 text-left text-sm text-danger-700 transition-colors hover:bg-danger/10"
            >
              <LogOut className="h-4 w-4" /> Keluar
            </button>
          </div>
        )}
      </div>
    </header>
  )
}

// apps/web/src/lib/components/dashboard/Sidebar.svelte
<script lang="ts">
  import { ChevronsUpDown, Settings, HelpCircle } from "lucide-svelte";
  import { auth } from "$lib/auth.store";
  import { navItemsForRoles, roleLabel } from "$lib/constants/navigation";

  let { onNavigate }: { onNavigate?: () => void } = $props();

  const user = $derived($auth.user);
  const sections = $derived(navItemsForRoles(user ? [user.role] : []));
  const initial = $derived((user?.fullName ?? user?.full_name ?? "?")[0].toUpperCase());

  function active(path: string) {
    if (typeof window === "undefined") return false;
    const p = window.location.pathname;
    return p === path || (path !== "/dashboard" && p.startsWith(path));
  }
</script>

<aside class="flex h-full w-60 flex-col border-r border-st-stroke bg-st-surface">
  <div class="flex h-14 items-center gap-2 border-b border-st-stroke px-4">
    <span class="accent-ring flex h-9 w-9 shrink-0 items-center justify-center rounded-full">
      <span class="flex h-[calc(100%-3px)] w-[calc(100%-3px)] items-center justify-center rounded-full bg-st-surface">
        <span class="font-display text-[15px] italic leading-none text-st-text">sf</span>
      </span>
    </span>
    <div class="min-w-0 flex-1">
      <p class="truncate font-display text-[15px] leading-none text-st-text">
        SIMTAS <span class="text-st-muted">FILKOM</span>
      </p>
    </div>
    <ChevronsUpDown size={14} class="shrink-0 text-st-muted" />
  </div>

  <nav class="flex-1 overflow-y-auto px-3 py-4">
    <div class="space-y-6">
      {#each sections as section, i (i)}
        <div>
          {#if section.title}
            <p class="mb-2 px-3 font-mono text-[0.7rem] uppercase tracking-[0.25em] text-st-muted">
              {section.title}
            </p>
          {/if}
          <div class="space-y-0.5">
            {#each section.items as item}
              {@const on = active(item.href)}
              <a
                href={item.href}
                onclick={onNavigate}
                class="accent-ring flex items-center gap-2.5 rounded-full px-3 py-1.5 text-[13px] font-medium transition-colors duration-100 {on
                  ? 'bg-st-surface-hi text-st-text'
                  : 'text-st-muted hover:bg-st-surface-hi hover:text-st-text'}"
              >
                <item.icon size={16} class="shrink-0 {on ? 'text-(--st-accent-to)' : ''}" />
                {item.label}
              </a>
            {/each}
          </div>
        </div>
      {/each}
    </div>

    <div class="mt-6 border-t border-st-stroke pt-4">
      <div class="space-y-0.5">
        <a
          href="/profile"
          onclick={onNavigate}
          class="flex items-center gap-2.5 rounded-full px-3 py-1.5 text-[13px] font-medium text-st-muted transition-colors hover:bg-st-surface-hi hover:text-st-text"
        >
          <Settings size={16} /> Pengaturan
        </a>
        <button
          type="button"
          class="flex w-full items-center gap-2.5 rounded-full px-3 py-1.5 text-[13px] font-medium text-st-muted transition-colors hover:bg-st-surface-hi hover:text-st-text"
          aria-label="Bantuan"
        >
          <HelpCircle size={16} /> Bantuan
        </button>
      </div>
    </div>
  </nav>

  <div class="border-t border-st-stroke px-3 py-2">
    <a
      href="/profile"
      onclick={onNavigate}
      class="accent-ring flex items-center gap-2.5 rounded-full px-2.5 py-2 text-sm transition-colors hover:bg-st-surface-hi"
    >
      <div class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-(--st-accent-from)/10 font-display text-[11px] italic text-(--st-accent-to)">
        {initial}
      </div>
      <div class="min-w-0 flex-1 leading-tight">
        <p class="truncate text-[13px] font-medium text-st-text">{user?.fullName ?? user?.full_name ?? "User"}</p>
        <p class="truncate text-[11px] text-st-muted">{roleLabel(user?.role)}</p>
      </div>
    </a>
  </div>
</aside>
