// frontend/src/components/features/dashboard/stat-card.tsx
import Link from 'next/link'
import { ArrowUpRight, type LucideIcon } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { NumberTicker } from '@/components/features/landing/number-ticker'
import { cn } from '@/lib/utils/cn'

export type StatTone = 'primary' | 'secondary' | 'success' | 'warning' | 'danger'

const TONE_CHIP: Record<StatTone, string> = {
  primary: 'bg-primary-50 text-primary',
  secondary: 'bg-secondary-50 text-secondary',
  success: 'bg-success-50 text-success',
  warning: 'bg-warning-50 text-warning',
  danger: 'bg-danger-50 text-danger',
}

export interface StatCardProps {
  title: string
  value: string | number
  icon: LucideIcon
  href?: string
  suffix?: string
  tone?: StatTone
}

export function StatCard({ title, value, icon: Icon, href, suffix, tone = 'primary' }: StatCardProps) {
  const inner = (
    <Card className="accent-ring h-full border-st-stroke bg-st-surface transition-colors">
      <CardContent className="p-5">
        <div className="flex items-center gap-3">
          <div className={cn('flex h-9 w-9 shrink-0 items-center justify-center rounded-full', TONE_CHIP[tone])}>
            <Icon className="h-4.5 w-4.5" aria-hidden />
          </div>
          <p className="font-mono text-[0.7rem] uppercase leading-tight tracking-[0.2em] text-st-muted">{title}</p>
        </div>
        <p className="mt-3 font-display text-3xl leading-none tabular-nums tracking-tight text-st-text">
          {typeof value === 'number' ? <NumberTicker value={value} /> : value}
          {suffix && <span className="ml-1 font-body text-sm font-normal text-st-muted">{suffix}</span>}
        </p>
      </CardContent>
    </Card>
  )

  if (!href) return inner

  return (
    <Link
      href={href}
      className="group block h-full rounded-2xl focus-visible:outline-none"
      aria-label={`${title}: ${value}`}
    >
      <div className="h-full rounded-2xl transition-shadow group-focus-visible:ring-2 group-focus-visible:ring-ring group-focus-visible:ring-offset-2">
        {inner}
      </div>
    </Link>
  )
}

export function ViewAllLink({ href, label = 'Lihat Semua' }: { href: string; label?: string }) {
  return (
    <Link
      href={href}
      className="inline-flex items-center gap-1 font-mono text-[0.7rem] uppercase tracking-[0.2em] text-(--st-accent-to) transition-colors hover:text-(--st-accent-from)"
    >
      {label}
      <ArrowUpRight className="h-3.5 w-3.5" />
    </Link>
  )
}

// apps/web/src/lib/components/dashboard/StatCard.svelte
<script lang="ts">
  import { ArrowUpRight } from "lucide-svelte";

  type IconComponent = typeof ArrowUpRight;
  import NumberTicker from "$lib/components/landing/NumberTicker.svelte";

  type StatTone = "primary" | "secondary" | "success" | "warning" | "danger";

  let {
    title,
    value,
    icon: Icon,
    href,
    suffix,
    tone = "primary",
  }: {
    title: string;
    value: string | number;
    icon?: IconComponent;
    href?: string;
    suffix?: string;
    tone?: StatTone;
  } = $props();

  const toneChip: Record<StatTone, string> = {
    primary: "bg-primary-50 text-primary",
    secondary: "bg-secondary-50 text-secondary-700",
    success: "bg-success-50 text-success",
    warning: "bg-warning-50 text-warning",
    danger: "bg-danger-50 text-danger-700",
  };
</script>

{#snippet inner()}
  <div class="h-full rounded-2xl border border-st-stroke bg-st-surface p-5 {Icon ? 'accent-ring' : ''}">
    {#if Icon}
      <div class="flex items-center gap-3">
        <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full {toneChip[tone]}">
          <Icon size={18} aria-hidden="true" />
        </div>
        <p class="font-mono text-[0.7rem] uppercase leading-tight tracking-[0.2em] text-st-muted">
          {title}
        </p>
      </div>
      <p class="mt-3 font-display text-3xl leading-none tabular-nums tracking-tight text-st-text">
        {#if typeof value === "number"}
          <NumberTicker {value} />
        {:else}
          {value}
        {/if}
        {#if suffix}<span class="ml-1 font-body text-sm font-normal text-st-muted">{suffix}</span>{/if}
      </p>
    {:else}
      <h3 class="landing-heading text-lg">{title}</h3>
      <p class="mt-2 font-display text-3xl leading-none tabular-nums tracking-tight text-st-text">
        {#if typeof value === "number"}
          <NumberTicker {value} />
        {:else}
          {value}
        {/if}
        {#if suffix}<span class="ml-1 font-body text-sm font-normal text-st-muted">{suffix}</span>{/if}
      </p>
    {/if}
  </div>
{/snippet}

{#if href}
  <a
    {href}
    class="group block h-full rounded-2xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
    aria-label="{title}: {value}"
  >
    {@render inner()}
  </a>
{:else}
  {@render inner()}
{/if}

<style>
  .accent-ring { position: relative; }
</style>
