// frontend/src/app/(dashboard)/supervision/page.tsx
'use client'

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { MessageSquarePlus, CheckCircle2, XCircle, Clock } from 'lucide-react'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Alert } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Spinner } from '@/components/ui/spinner'
import { consultationApi } from '@/lib/api/consultation-api'
import { getErrorMessage } from '@/lib/utils/error'
import { formatDate } from '@/lib/utils/date'
import { useAuthStore } from '@/lib/stores/auth-store'
import { useThesisPicker } from '@/lib/hooks/use-thesis-picker'
import type { Consultation } from '@/types/consultation'

const consultSchema = z.object({
  date: z.string().min(1, 'Tanggal wajib diisi'),
  topic: z.string().min(3, 'Topik wajib diisi'),
  notes: z.string().optional(),
  follow_up: z.string().optional(),
})

type ConsultForm = z.infer<typeof consultSchema>

function statusBadge(status: string) {
  switch (status) {
    case 'approved':
      return <Badge variant="success"><CheckCircle2 className="h-3 w-3" /> Disetujui</Badge>
    case 'rejected':
      return <Badge variant="danger"><XCircle className="h-3 w-3" /> Ditolak</Badge>
    default:
      return <Badge variant="warning"><Clock className="h-3 w-3" /> Menunggu</Badge>
  }
}

export default function SupervisionPage() {
  const { user } = useAuthStore()
  const queryClient = useQueryClient()
  const isStudent = user?.role === 'mahasiswa'
  const [showForm, setShowForm] = useState(false)
  const [actionError, setActionError] = useState<string | null>(null)

  // Mahasiswa: skripsi sendiri. Dosen/staf: pilih mahasiswa bimbingan lewat picker.
  const { thesis: myThesis, picker, isLoading: thesesLoading } = useThesisPicker()

  const consultations = useQuery({
    queryKey: ['consultations', myThesis?.id],
    queryFn: () => (myThesis?.id ? consultationApi.list(myThesis.id, { per_page: 50 }) : Promise.resolve(null)),
    enabled: Boolean(myThesis?.id),
  })

  const list = consultations.data?.data ?? []

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<ConsultForm>({ resolver: zodResolver(consultSchema) })

  const create = useMutation({
    mutationFn: (data: ConsultForm) => {
      if (!myThesis?.id) throw new Error('Tidak ada skripsi aktif')
      return consultationApi.create(myThesis.id, data)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['consultations'] })
      queryClient.invalidateQueries({ queryKey: ['dashboard', 'student'] })
      reset()
      setShowForm(false)
    },
  })

  const approve = useMutation({
    mutationFn: (c: Consultation) => {
      if (!myThesis?.id) throw new Error('Tidak ada skripsi')
      return consultationApi.approve(myThesis.id, c.id)
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['consultations'] }),
  })

  if (thesesLoading) return <Spinner label="Memuat data…" />

  if (!myThesis) {
    return (
      <Card>
        <CardContent className="py-14 text-center">
          <MessageSquarePlus className="mx-auto h-10 w-10 text-muted-foreground" />
          <p className="mt-4 text-lg font-semibold">Belum ada skripsi aktif</p>
          <p className="mt-1 text-sm text-muted-foreground">
            {isStudent ? 'Ajukan skripsi Anda terlebih dahulu untuk mulai bimbingan.' : 'Belum ada mahasiswa yang Anda bimbing.'}
          </p>
        </CardContent>
      </Card>
    )
  }

  const onSubmit = handleSubmit(async (data) => {
    setActionError(null)
    try {
      await create.mutateAsync(data)
    } catch (err) {
      setActionError(getErrorMessage(err, 'Gagal menyimpan bimbingan.'))
    }
  })

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold">Bimbingan</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            {isStudent ? 'Catatan bimbingan dengan dosen pembimbing Anda' : 'Catatan bimbingan mahasiswa Anda'}
          </p>
          {!isStudent && picker}
        </div>
        {isStudent && (
          <Button onClick={() => setShowForm((v) => !v)}>
            <MessageSquarePlus className="h-4 w-4" /> Catat Bimbingan
          </Button>
        )}
      </div>

      {showForm && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Catat Bimbingan Baru</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={onSubmit} noValidate className="space-y-4">
              {actionError && <Alert variant="danger">{actionError}</Alert>}
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <Label htmlFor="date" required>Tanggal</Label>
                  <Input id="date" type="date" invalid={!!errors.date} {...register('date')} />
                  {errors.date && <p className="mt-1 text-xs text-danger">{errors.date.message}</p>}
                </div>
                <div>
                  <Label htmlFor="topic" required>Topik / Materi</Label>
                  <Input id="topic" placeholder="mis. Revisi Bab 2" invalid={!!errors.topic} {...register('topic')} />
                  {errors.topic && <p className="mt-1 text-xs text-danger">{errors.topic.message}</p>}
                </div>
              </div>
              <div>
                <Label htmlFor="notes">Catatan</Label>
                <Textarea id="notes" rows={3} placeholder="Hasil diskusi…" {...register('notes')} />
              </div>
              <div>
                <Label htmlFor="follow_up">Tindak Lanjut</Label>
                <Textarea id="follow_up" rows={2} placeholder="Pekerjaan selanjutnya…" {...register('follow_up')} />
              </div>
              <div className="flex gap-3">
                <Button type="submit" loading={create.isPending}>Simpan</Button>
                <Button type="button" variant="ghost" onClick={() => setShowForm(false)}>Batal</Button>
              </div>
            </form>
          </CardContent>
        </Card>
      )}

      <div className="space-y-3">
        {consultations.isLoading && <Spinner />}
        {list.map((c) => (
          <Card key={c.id}>
            <CardContent className="p-5">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <p className="font-medium">{c.topic}</p>
                    {statusBadge(c.status)}
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">
                    {formatDate(c.date)}
                    {c.student_name && ` · ${c.student_name}`}
                    {c.supervisor_name && ` · ${c.supervisor_name}`}
                  </p>
                </div>
                {!isStudent && c.status === 'pending' && (
                  <Button size="sm" variant="success" onClick={() => approve.mutate(c)}>
                    <CheckCircle2 className="h-3.5 w-3.5" /> Setujui
                  </Button>
                )}
              </div>
              {c.notes && <p className="mt-3 text-sm leading-relaxed">{c.notes}</p>}
              {c.follow_up && (
                <p className="mt-2 text-sm text-muted-foreground">
                  <span className="font-medium">Tindak lanjut:</span> {c.follow_up}
                </p>
              )}
            </CardContent>
          </Card>
        ))}
        {!consultations.isLoading && list.length === 0 && (
          <p className="py-10 text-center text-sm text-muted-foreground">Belum ada catatan bimbingan.</p>
        )}
      </div>
    </div>
  )
}

// apps/web/src/routes/dashboard/supervision/+page.svelte
<script lang="ts">
  import { MessageSquarePlus, Check, Calendar, User } from "lucide-svelte";
  import { api } from "$lib/api";
  import { auth } from "$lib/auth.store";
  import StatCard from "$lib/components/dashboard/StatCard.svelte";
  import StatusBadge from "$lib/components/dashboard/StatusBadge.svelte";
  import Reveal from "$lib/components/landing/Reveal.svelte";
  import { thesisStatusProps, type StatusVariant } from "$lib/components/dashboard/thesis-status";

  let thesisId = $state("");
  let status = $state("");
  let page = $state(1);
  let list = $state<any[]>([]);
  let total = $state(0);
  let summary = $state<{ total?: number; approved?: number; pending?: number } | null>(null);
  let loading = $state(true);
  let error = $state("");
  let actionError = $state("");

  const isStudent = $derived(($auth.user as any)?.role === "mahasiswa");

  function variantFor(s: string): StatusVariant {
    const v = thesisStatusProps(s).variant;
    return v;
  }
  function labelFor(s: string): string {
    return thesisStatusProps(s).label;
  }

  async function load() {
    loading = true;
    error = "";
    try {
      const query: Record<string, string> = { page: String(page), per_page: "20" };
      if (thesisId) query.thesisId = thesisId;
      if (status) query.status = status;
      const res = await api.api.v1.consultationLogs.$get({ query });
      const json: any = res.ok ? await res.json() : null;
      list = json?.data ?? [];
      total = json?.meta?.total ?? list.length;
      summary = json?.summary ?? null;

      if (!thesisId && isStudent) {
        const me: any = ($auth.user as any) ?? {};
        if (me.thesisId) thesisId = me.thesisId;
      }
      if (thesisId) {
        const sumRes = await api.api.v1.consultationLogs.summary.$get({ query: { thesisId } });
        const sumJson: any = sumRes.ok ? await sumRes.json() : null;
        if (sumJson?.data) summary = sumJson.data;
      }
    } catch (e) {
      error = "Gagal memuat catatan bimbingan.";
    } finally {
      loading = false;
    }
  }

  $effect(() => {
    thesisId; status; page;
    load();
  });

  async function approve(id: string) {
    actionError = "";
    try {
      if (!thesisId) {
        actionError = "thesisId belum dipilih.";
        return;
      }
      const res = await api.api.v1.consultationLogs[":id"].approve.$patch({
        param: { id },
        query: { thesisId },
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        actionError = (body as any)?.error?.message ?? "Gagal menyetujui bimbingan.";
        return;
      }
      await load();
    } catch (e) {
      actionError = "Gagal menyetujui bimbingan.";
    }
  }

  function formatDate(s?: string) {
    if (!s) return "—";
    try {
      return new Date(s).toLocaleDateString("id-ID", { day: "2-digit", month: "short", year: "numeric" });
    } catch {
      return s;
    }
  }
</script>

<div class="space-y-6">
  <Reveal>
    <div class="flex flex-wrap items-end justify-between gap-3">
      <div>
        <p class="landing-eyebrow">Catatan Bimbingan</p>
        <h1 class="mt-2 text-balance landing-heading text-2xl">
          {#if isStudent}
            Bimbingan <span class="accent-text italic">Anda</span>
          {:else}
            Bimbingan <span class="accent-text italic">Mahasiswa</span>
          {/if}
        </h1>
        <p class="mt-1.5 text-sm text-st-muted">
          {isStudent
            ? "Catatan bimbingan dengan dosen pembimbing Anda"
            : "Catatan bimbingan mahasiswa yang Anda bimbing"}
        </p>
      </div>
    </div>
  </Reveal>

  {#if summary}
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-3">
      <StatCard title="Total" value={summary.total ?? list.length} icon={MessageSquarePlus} tone="primary" />
      <StatCard title="Disetujui" value={summary.approved ?? 0} icon={Check} tone="success" />
      <StatCard title="Menunggu" value={summary.pending ?? 0} icon={Calendar} tone="warning" />
    </div>
  {/if}

  <div class="flex flex-wrap items-center gap-3">
    {#if !isStudent}
      <input
        type="search"
        placeholder="Thesis ID (UUID)…"
        bind:value={thesisId}
        oninput={() => (page = 1)}
        class="w-full max-w-xs rounded-md border border-st-stroke bg-st-surface px-3 py-2 text-sm text-st-text outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring"
      />
    {/if}
    <select
      bind:value={status}
      onchange={() => (page = 1)}
      class="w-44 rounded-md border border-st-stroke bg-st-surface px-3 py-2 text-sm text-st-text outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring"
    >
      <option value="">Semua status</option>
      <option value="pending">Menunggu</option>
      <option value="approved">Disetujui</option>
      <option value="rejected">Ditolak</option>
    </select>
  </div>

  {#if actionError}
    <div role="alert" class="rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
      {actionError}
    </div>
  {/if}
  {#if error}
    <div role="alert" class="rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
      {error}
    </div>
  {/if}

  {#if loading}
    <div class="py-10 text-center text-sm text-st-muted">Memuat catatan bimbingan…</div>
  {:else}
    <div class="space-y-3">
      {#each list as c (c.id)}
        {@const variant = variantFor(c.status ?? "")}
        {@const label = labelFor(c.status ?? "")}
        {@const date = c.consultationDate ?? c.consultation_date ?? c.date}
        {@const studentName = c.studentName ?? c.student_name ?? c.student?.fullName ?? c.student?.full_name}
        <article class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-st-stroke bg-st-surface p-5">
          <div class="flex min-w-0 items-center gap-3">
            <div class="accent-ring flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-(--st-accent-from)/10 text-(--st-accent-to)">
              <MessageSquarePlus size={20} />
            </div>
            <div class="min-w-0">
              <div class="flex flex-wrap items-center gap-2">
                <p class="font-medium text-st-text">
                  {c.thesisTitle ?? c.thesis_title ?? "Bimbingan"}
                </p>
                <StatusBadge {variant} {label} />
              </div>
              <p class="mt-0.5 line-clamp-1 text-sm text-st-muted">
                {c.topicsDiscussed ?? c.topics_discussed ?? c.topic ?? "—"}
              </p>
              <p class="mt-1 flex flex-wrap items-center gap-3 text-xs text-st-muted">
                <span class="inline-flex items-center gap-1">
                  <Calendar size={12} aria-hidden="true" /> {formatDate(date)}
                </span>
                {#if studentName}
                  <span class="inline-flex items-center gap-1">
                    <User size={12} aria-hidden="true" /> {studentName}
                  </span>
                {/if}
              </p>
            </div>
          </div>
          {#if !isStudent && (c.status === "pending" || !c.status)}
            <button
              type="button"
              onclick={() => approve(c.id)}
              class="inline-flex h-8 items-center gap-1.5 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary-700"
            >
              <Check size={14} aria-hidden="true" /> Setujui
            </button>
          {/if}
        </article>
      {/each}
      {#if list.length === 0}
        <div class="rounded-2xl border border-st-stroke bg-st-surface py-12 text-center">
          <MessageSquarePlus size={36} class="mx-auto text-st-muted" />
          <p class="mt-3 landing-heading text-lg">
            Belum ada <span class="accent-text italic">catatan bimbingan</span>
          </p>
          <p class="mt-1 text-sm text-st-muted">Mulai dengan mencatat sesi bimbingan pertama Anda.</p>
        </div>
      {/if}
    </div>
  {/if}

  {#if total > 20}
    <div class="flex items-center justify-between pt-2">
      <p class="text-sm text-st-muted">Total {total} catatan · Halaman {page}</p>
      <div class="flex gap-2">
        <button
          type="button"
          disabled={page <= 1}
          onclick={() => (page -= 1)}
          class="inline-flex h-8 items-center rounded-md border border-st-stroke bg-st-surface px-3 text-sm text-st-text hover:bg-st-surface-hi disabled:opacity-50"
        >
          Sebelumnya
        </button>
        <button
          type="button"
          disabled={page >= Math.ceil(total / 20)}
          onclick={() => (page += 1)}
          class="inline-flex h-8 items-center rounded-md border border-st-stroke bg-st-surface px-3 text-sm text-st-text hover:bg-st-surface-hi disabled:opacity-50"
        >
          Berikutnya
        </button>
      </div>
    </div>
  {/if}
</div>
