// apps/web/src/routes/dashboard/thesis/+page.svelte
<script lang="ts">
  import { BookOpen, CheckCircle2, Clock, History, PencilLine, XCircle } from "lucide-svelte";
  import { api } from "$lib/api";
  import { auth } from "$lib/auth.store";
  import StatusBadge from "$lib/components/dashboard/StatusBadge.svelte";
  import { thesisStatusProps } from "$lib/components/dashboard/thesis-status";
  import Reveal from "$lib/components/landing/Reveal.svelte";

  const user = $derived($auth.user);

  let thesis = $state<any | null>(null);
  let requests = $state<any[]>([]);
  let loading = $state(true);
  let error = $state("");
  let requestsLoading = $state(false);
  let submitOpen = $state(false);
  let cancelTarget = $state<any | null>(null);
  let actionError = $state<string | null>(null);
  let submitting = $state(false);
  let cancelling = $state(false);
  let cancelError = $state<string | null>(null);

  let newTitle = $state("");
  let newReason = $state("");
  let titleError = $state<string | null>(null);

  function errorMessage(err: any, fallback: string): string {
    return err?.error?.message ?? err?.message ?? fallback;
  }

  function formatDate(s?: string | null) {
    if (!s) return "—";
    try {
      return new Date(s).toLocaleDateString("id-ID", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      });
    } catch {
      return s;
    }
  }

  function titleChangeBadge(status: string) {
    switch (status) {
      case "PENDING":
        return { class: "bg-warning-50 text-warning border border-warning/20", label: "Menunggu Persetujuan" };
      case "APPROVED":
        return { class: "bg-success-50 text-success border border-success/20", label: "Disetujui" };
      case "REJECTED":
        return { class: "bg-danger-50 text-danger-700 border border-danger/20", label: "Ditolak" };
      default:
        return { class: "bg-st-surface-hi text-st-muted border border-st-stroke", label: "Dibatalkan" };
    }
  }

  async function loadThesis() {
    loading = true;
    error = "";
    try {
      const res = await api.api.v1.theses.$get({ query: { page: "1", per_page: "1" } });
      if (!res.ok) throw await res.json();
      const json: any = await res.json();
      const list = json?.data ?? [];
      const own = user?.id ? list.find((t: any) => (t.student?.id ?? t.studentId) === user.id) ?? list[0] : list[0];
      thesis = own ?? null;
    } catch (e: any) {
      error = errorMessage(e, "Gagal memuat skripsi.");
    } finally {
      loading = false;
    }
  }

  async function loadRequests(id: string) {
    requestsLoading = true;
    try {
      const res = await api.api.v1.titleChangeRequests.$get({});
      if (!res.ok) throw await res.json();
      const json: any = await res.json();
      const all: any[] = json?.data ?? [];
      requests = all.filter((r: any) => (r.thesisId ?? r.thesis_id) === id);
    } catch {
      requests = [];
    } finally {
      requestsLoading = false;
    }
  }

  $effect(() => {
    if ($auth.accessToken) loadThesis();
  });

  $effect(() => {
    if (thesis?.id) loadRequests(thesis.id);
  });

  const sp = $derived(thesis ? thesisStatusProps(thesis.status ?? "") : null);
  const hasPending = $derived(requests.some((r) => r.status === "PENDING"));
  const canRequest = $derived(
    user?.role === "mahasiswa" &&
      thesis &&
      (thesis.status === "approved" || thesis.status === "in_progress") &&
      (thesis.supervisors?.length ?? 0) > 0 &&
      !hasPending,
  );

  function openSubmit() {
    newTitle = "";
    newReason = "";
    titleError = null;
    actionError = null;
    submitOpen = true;
  }

  function closeSubmit() {
    submitOpen = false;
  }

  function validateTitle(value: string): string | null {
    const v = value.trim();
    if (!v) return "Judul baru wajib diisi";
    if (v.length > 500) return "Judul maksimal 500 karakter";
    const words = v.split(/\s+/).filter(Boolean).length;
    if (words < 10) return "Judul minimal 10 kata";
    return null;
  }

  async function onSubmitChange() {
    if (!thesis?.id) return;
    const tErr = validateTitle(newTitle);
    if (tErr) {
      titleError = tErr;
      return;
    }
    titleError = null;
    actionError = null;
    submitting = true;
    try {
      const res = await api.api.v1.titleChangeRequests.$post({
        json: {
          thesisId: thesis.id,
          requestedTitle: newTitle.trim(),
          reason: newReason.trim() || undefined,
        },
      });
      if (!res.ok) {
        const body = await res.json().catch(() => null);
        throw new Error((body as any)?.error?.message ?? "Gagal mengajukan perubahan judul.");
      }
      submitOpen = false;
      await loadRequests(thesis.id);
    } catch (e: any) {
      actionError = errorMessage(e, "Gagal mengajukan perubahan judul.");
    } finally {
      submitting = false;
    }
  }

  function openCancel(req: any) {
    cancelError = null;
    cancelTarget = req;
  }

  function closeCancel() {
    cancelTarget = null;
  }

  async function confirmCancel() {
    if (!cancelTarget?.id) return;
    cancelling = true;
    cancelError = null;
    try {
      const res = await api.api.v1.titleChangeRequests[cancelTarget.id].cancel.$patch({});
      if (!res.ok) {
        const body = await res.json().catch(() => null);
        throw new Error((body as any)?.error?.message ?? "Gagal membatalkan permintaan.");
      }
      cancelTarget = null;
      if (thesis?.id) await loadRequests(thesis.id);
    } catch (e: any) {
      cancelError = errorMessage(e, "Gagal membatalkan permintaan.");
    } finally {
      cancelling = false;
    }
  }
</script>

<div class="space-y-6">
  <div class="flex flex-wrap items-center justify-between gap-3">
    <div>
      <p class="landing-eyebrow">Tugas Akhir Skripsi Saya</p>
      <h1 class="mt-2 text-balance landing-heading text-2xl">
        Skripsi <span class="accent-text italic">Saya</span>
      </h1>
    </div>
    {#if !loading && thesis}
      <div class="flex flex-wrap items-center gap-2">
        {#if canRequest}
          <button
            type="button"
            onclick={openSubmit}
            class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary-700"
          >
            <PencilLine size={16} /> Ajukan Perubahan Judul
          </button>
        {/if}
        <a
          href="/thesis/new"
          class="inline-flex h-9 items-center justify-center rounded-md border border-st-stroke bg-st-surface px-3 text-sm font-medium text-st-text transition-colors hover:bg-st-surface-hi"
        >
          Ajukan Judul Baru
        </a>
      </div>
    {/if}
  </div>

  {#if loading}
    <div class="rounded-2xl border border-st-stroke bg-st-surface p-6 text-sm text-st-muted">
      Memuat skripsi…
    </div>
  {:else if error}
    <div role="alert" class="rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
      {error}
    </div>
  {:else if !thesis}
    <Reveal>
      <div class="mx-auto max-w-lg space-y-6 rounded-2xl border border-st-stroke bg-st-surface py-10 text-center">
        <div class="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-primary-50 text-primary">
          <BookOpen size={32} />
        </div>
        <div>
          <h2 class="text-xl font-bold text-st-text">Anda belum memiliki skripsi</h2>
          <p class="mt-2 text-sm text-st-muted">
            Ajukan judul skripsi Anda untuk memulai perjalanan Tugas Akhir.
          </p>
        </div>
        <a
          href="/thesis/new"
          class="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary-700"
        >
          Ajukan Judul Skripsi
        </a>
      </div>
    </Reveal>
  {:else}
    <Reveal>
      <article class="rounded-2xl border border-st-stroke bg-st-surface p-6">
        <div class="flex flex-wrap items-start justify-between gap-3">
          <div class="space-y-1.5">
            <h2 class="text-xl leading-snug text-st-text">{thesis.title}</h2>
            {#if sp}
              <StatusBadge variant={sp.variant} label={sp.label} />
            {/if}
          </div>
        </div>

        <div class="mt-4 space-y-4">
          {#if thesis.abstract}
            <div>
              <p class="mb-1 text-sm font-medium text-st-muted">Abstrak</p>
              <p class="text-sm leading-relaxed text-st-text">{thesis.abstract}</p>
            </div>
          {/if}
          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div>
              <p class="text-sm font-medium text-st-muted">Bidang Keahlian</p>
              <p class="text-sm text-st-text">{thesis.fieldOfStudy ?? thesis.field_of_study ?? "—"}</p>
            </div>
            <div>
              <p class="text-sm font-medium text-st-muted">Pembimbing</p>
              <p class="text-sm text-st-text">
                {thesis.supervisors?.length
                  ? thesis.supervisors.map((s: any) => s.fullName ?? s.full_name).join(", ")
                  : "Belum ditentukan"}
              </p>
            </div>
          </div>
          {#if thesis.kaprodiNotes ?? thesis.kaprodi_notes}
            <div class="rounded-lg border border-secondary/30 bg-secondary-50 p-4">
              <p class="text-sm font-medium text-secondary-foreground">Catatan Kaprodi</p>
              <p class="mt-1 text-sm text-st-text">{thesis.kaprodiNotes ?? thesis.kaprodi_notes}</p>
            </div>
          {/if}
        </div>
      </article>
    </Reveal>

    <Reveal delay={80}>
      <article class="rounded-2xl border border-st-stroke bg-st-surface p-6">
        <div class="flex items-center justify-between gap-2">
          <div class="space-y-1">
            <h3 class="flex items-center gap-2 text-base font-medium text-st-text">
              <History size={16} class="text-primary" /> Riwayat Perubahan Judul
            </h3>
            <p class="text-sm text-st-muted">
              Pengajuan dan hasil review perubahan judul skripsi Anda
            </p>
          </div>
        </div>

        <div class="mt-4">
          {#if requestsLoading}
            <p class="py-6 text-center text-sm text-st-muted">Memuat riwayat…</p>
          {:else if requests.length === 0}
            <p class="py-6 text-center text-sm text-st-muted">
              Belum ada pengajuan perubahan judul.
            </p>
          {:else}
            <div class="space-y-3">
              {#each requests as r (r.id)}
                {@const rb = titleChangeBadge(r.status)}
                <div class="rounded-xl border border-st-stroke p-4">
                  <div class="flex flex-wrap items-start justify-between gap-2">
                    <div class="min-w-0 flex-1">
                      <div class="flex flex-wrap items-center gap-2">
                        <p class="font-medium text-st-text">Judul baru: {r.requestedTitle ?? r.requested_title}</p>
                        <span class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[11px] font-medium {rb.class}">
                          {#if r.status === "PENDING"}
                            <Clock size={12} />
                          {:else if r.status === "APPROVED"}
                            <CheckCircle2 size={12} />
                          {:else if r.status === "REJECTED"}
                            <XCircle size={12} />
                          {/if}
                          {rb.label}
                        </span>
                      </div>
                      <p class="mt-1 text-xs text-st-muted">
                        Diajukan {formatDate(r.createdAt ?? r.created_at)}
                        {#if r.requestedBy?.fullName ?? r.requested_by?.full_name}
                          oleh {r.requestedBy?.fullName ?? r.requested_by?.full_name}
                        {/if}
                      </p>
                    </div>
                    {#if r.status === "PENDING"}
                      <button
                        type="button"
                        onclick={() => openCancel(r)}
                        class="inline-flex h-8 items-center gap-1.5 rounded-md px-2 text-sm font-medium text-danger-700 transition-colors hover:bg-danger-50"
                      >
                        <XCircle size={14} /> Batalkan
                      </button>
                    {/if}
                  </div>

                  <div class="mt-3 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
                    <div class="rounded-lg bg-st-bg p-3">
                      <p class="text-xs font-medium text-st-muted">Judul Sebelumnya</p>
                      <p class="mt-0.5 leading-snug text-st-text line-through decoration-st-muted/40">
                        {r.previousTitle ?? r.previous_title}
                      </p>
                    </div>
                    <div class="rounded-lg bg-primary-50 p-3">
                      <p class="text-xs font-medium text-primary-700">Judul yang Diajukan</p>
                      <p class="mt-0.5 leading-snug text-st-text">
                        {r.requestedTitle ?? r.requested_title}
                      </p>
                    </div>
                  </div>

                  {#if r.reason}
                    <p class="mt-3 text-sm text-st-text">
                      <span class="font-medium text-st-muted">Alasan: </span>{r.reason}
                    </p>
                  {/if}

                  {#if ((r.reviewedBy?.fullName ?? r.reviewed_by?.full_name) || r.reviewNotes) || r.review_notes}
                    <div class="mt-3 border-t border-st-stroke pt-3 text-sm">
                      {#if r.reviewedBy?.fullName ?? r.reviewed_by?.full_name}
                        <p class="text-st-muted">
                          <span class="font-medium text-st-text">Direview oleh:</span>
                          {r.reviewedBy?.fullName ?? r.reviewed_by?.full_name}
                        </p>
                      {/if}
                      {#if r.reviewNotes ?? r.review_notes}
                        <p class="mt-1 text-st-muted">
                          <span class="font-medium text-st-text">Catatan Pembimbing:</span>
                          {r.reviewNotes ?? r.review_notes}
                        </p>
                      {/if}
                    </div>
                  {/if}
                </div>
              {/each}
            </div>
          {/if}
        </div>
      </article>
    </Reveal>
  {/if}
</div>

{#if submitOpen}
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="submit-title">
    <button
      type="button"
      class="absolute inset-0 bg-black/40"
      onclick={closeSubmit}
      aria-label="Tutup dialog"
    ></button>
    <div class="relative z-10 w-full max-w-lg rounded-2xl border border-st-stroke bg-st-surface p-6">
      <h2 id="submit-title" class="text-lg font-semibold text-st-text">Ajukan Perubahan Judul</h2>
      <p class="mt-1 text-sm text-st-muted">
        Perubahan judul akan diproses oleh Dosen Pembimbing Anda.
      </p>

      <form
        class="mt-4 space-y-4"
        onsubmit={(e) => {
          e.preventDefault();
          onSubmitChange();
        }}
      >
        {#if actionError}
          <div role="alert" class="rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
            {actionError}
          </div>
        {/if}
        <div>
          <label for="current-title" class="text-sm font-medium text-st-text">Judul Saat Ini</label>
          <input
            id="current-title"
            type="text"
            readonly
            value={thesis?.title ?? ""}
            class="mt-1 w-full rounded-md border border-st-stroke bg-st-bg px-3 py-2 text-sm text-st-muted"
          />
        </div>
        <div>
          <label for="requested-title" class="text-sm font-medium text-st-text">Judul Baru <span class="text-danger-700">*</span></label>
          <textarea
            id="requested-title"
            rows="3"
            placeholder="Tulis judul baru skripsi Anda (minimal 10 kata)"
            bind:value={newTitle}
            class="mt-1 w-full rounded-md border {titleError ? 'border-danger-700' : 'border-st-stroke'} bg-st-surface px-3 py-2 text-sm text-st-text outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring"
          ></textarea>
          {#if titleError}
            <p class="mt-1 text-xs text-danger-700">{titleError}</p>
          {/if}
        </div>
        <div>
          <label for="reason" class="text-sm font-medium text-st-text">Alasan Perubahan</label>
          <textarea
            id="reason"
            rows="2"
            placeholder="Alasan mengajukan perubahan judul (opsional)"
            bind:value={newReason}
            class="mt-1 w-full rounded-md border border-st-stroke bg-st-surface px-3 py-2 text-sm text-st-text outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-ring"
          ></textarea>
        </div>
        <div class="flex flex-wrap justify-end gap-2 pt-1">
          <button
            type="button"
            onclick={closeSubmit}
            class="inline-flex h-9 items-center rounded-md px-3 text-sm font-medium text-st-text transition-colors hover:bg-st-surface-hi"
          >
            Batal
          </button>
          <button
            type="submit"
            disabled={submitting}
            class="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary-700 disabled:opacity-50"
          >
            <PencilLine size={16} /> {submitting ? "Mengajukan…" : "Ajukan"}
          </button>
        </div>
      </form>
    </div>
  </div>
{/if}

{#if cancelTarget}
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="cancel-title">
    <button
      type="button"
      class="absolute inset-0 bg-black/40"
      onclick={closeCancel}
      aria-label="Tutup dialog"
    ></button>
    <div class="relative z-10 w-full max-w-md rounded-2xl border border-st-stroke bg-st-surface p-6">
      <h2 id="cancel-title" class="text-lg font-semibold text-st-text">
        Batalkan Permintaan Perubahan Judul?
      </h2>
      <p class="mt-1 text-sm text-st-muted">
        Permintaan yang sedang diproses akan ditarik dan tidak dapat dikembalikan.
      </p>

      <div class="mt-4 space-y-4">
        <div class="rounded-lg bg-st-bg p-3 text-sm">
          <p class="text-xs font-medium text-st-muted">Judul yang diajukan</p>
          <p class="mt-0.5 text-st-text">
            {cancelTarget.requestedTitle ?? cancelTarget.requested_title}
          </p>
        </div>
        {#if cancelError}
          <div role="alert" class="rounded-md border border-danger-700/40 bg-danger-50 px-3 py-2 text-sm text-danger-700">
            {cancelError}
          </div>
        {/if}
        <div class="flex flex-wrap justify-end gap-2">
          <button
            type="button"
            onclick={closeCancel}
            class="inline-flex h-9 items-center rounded-md px-3 text-sm font-medium text-st-text transition-colors hover:bg-st-surface-hi"
          >
            Kembali
          </button>
          <button
            type="button"
            disabled={cancelling}
            onclick={confirmCancel}
            class="inline-flex h-9 items-center rounded-md border border-danger-700/40 bg-danger-50 px-3 text-sm font-medium text-danger-700 transition-colors hover:bg-danger-100 disabled:opacity-50"
          >
            {cancelling ? "Membatalkan…" : "Ya, Batalkan"}
          </button>
        </div>
      </div>
    </div>
  </div>
{/if}

// frontend/src/app/(dashboard)/thesis/page.tsx
'use client'

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { BookOpen, CheckCircle2, Clock, History, PencilLine, XCircle } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'
import { Alert } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Spinner } from '@/components/ui/spinner'
import { Textarea } from '@/components/ui/textarea'
import { thesisApi } from '@/lib/api/thesis-api'
import { titleChangeApi } from '@/lib/api/title-change-api'
import { toast } from '@/components/ui/toaster'
import { useAuthStore } from '@/lib/stores/auth-store'
import { getErrorMessage } from '@/lib/utils/error'
import { formatDate } from '@/lib/utils/date'
import type { TitleChangeRequest, TitleChangeStatus } from '@/types/title-change'

function statusVariant(status: string) {
  switch (status) {
    case 'graduated':
      return 'success'
    case 'cancelled':
      return 'danger'
    case 'rejected':
      return 'danger'
    case 'submitted':
      return 'warning'
    default:
      return 'primary'
  }
}

function titleChangeBadge(status: TitleChangeStatus) {
  switch (status) {
    case 'PENDING':
      return <Badge variant="warning"><Clock className="h-3 w-3" /> Menunggu Persetujuan</Badge>
    case 'APPROVED':
      return <Badge variant="success"><CheckCircle2 className="h-3 w-3" /> Disetujui</Badge>
    case 'REJECTED':
      return <Badge variant="danger"><XCircle className="h-3 w-3" /> Ditolak</Badge>
    default:
      return <Badge variant="muted">Dibatalkan</Badge>
  }
}

const submitSchema = z.object({
  requested_title: z
    .string()
    .min(1, 'Judul baru wajib diisi')
    .max(500, 'Judul maksimal 500 karakter')
    .refine((v) => v.trim().split(/\s+/).filter(Boolean).length >= 10, 'Judul minimal 10 kata'),
  reason: z.string().optional(),
})

type SubmitForm = z.infer<typeof submitSchema>

export default function MyThesisPage() {
  const { user } = useAuthStore()
  const queryClient = useQueryClient()
  const [submitOpen, setSubmitOpen] = useState(false)
  const [cancelTarget, setCancelTarget] = useState<TitleChangeRequest | null>(null)
  const [actionError, setActionError] = useState<string | null>(null)

  const theses = useQuery({
    queryKey: ['theses', 'mine'],
    queryFn: () => thesisApi.list({ per_page: 1 }),
    enabled: Boolean(user),
  })

  const list = theses.data?.data ?? []
  const thesis = list[0]

  const requests = useQuery({
    queryKey: ['title-change', thesis?.id],
    queryFn: () => (thesis?.id ? titleChangeApi.list(thesis.id) : Promise.resolve([])),
    enabled: Boolean(thesis?.id),
  })

  const changeRequests = requests.data ?? []
  const hasPending = changeRequests.some((r) => r.status === 'PENDING')

  // Tombol pengajuan hanya muncul untuk pemilik skripsi dengan status
  // approved/in_progress, ada pembimbing aktif, dan belum ada request PENDING.
  const canRequest =
    user?.role === 'mahasiswa' &&
    thesis &&
    (thesis.status === 'approved' || thesis.status === 'in_progress') &&
    (thesis.supervisors?.length ?? 0) > 0 &&
    !hasPending

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<SubmitForm>({ resolver: zodResolver(submitSchema) })

  const submit = useMutation({
    mutationFn: (data: SubmitForm) => {
      if (!thesis?.id) throw new Error('Tidak ada skripsi aktif')
      return titleChangeApi.create(thesis.id, { requested_title: data.requested_title, reason: data.reason || undefined })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['title-change'] })
      setSubmitOpen(false)
      reset()
      setActionError(null)
      toast({ variant: 'success', title: 'Perubahan judul diajukan', description: 'Menunggu persetujuan Dosen Pembimbing.' })
    },
  })

  const cancelReq = useMutation({
    mutationFn: (id: string) => titleChangeApi.cancel(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['title-change'] })
      setCancelTarget(null)
      toast({ variant: 'success', title: 'Permintaan dibatalkan' })
    },
  })

  const onSubmit = handleSubmit(async (data) => {
    setActionError(null)
    try {
      await submit.mutateAsync(data)
    } catch (err) {
      setActionError(getErrorMessage(err, 'Gagal mengajukan perubahan judul.'))
    }
  })

  if (theses.isLoading) return <Spinner label="Memuat skripsi…" />

  if (!thesis) {
    return (
      <div className="mx-auto max-w-lg space-y-6 py-10 text-center">
        <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-primary-50 text-primary">
          <BookOpen className="h-8 w-8" />
        </div>
        <div>
          <h1 className="text-xl font-bold">Anda belum memiliki skripsi</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Ajukan judul skripsi Anda untuk memulai perjalanan Tugas Akhir.
          </p>
        </div>
        <Button asChild size="lg">
          <Link href="/thesis/new">Ajukan Judul Skripsi</Link>
        </Button>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-2xl font-bold">Skripsi Saya</h1>
        <div className="flex flex-wrap items-center gap-2">
          {canRequest && (
            <Button size="sm" onClick={() => setSubmitOpen(true)}>
              <PencilLine className="h-4 w-4" /> Ajukan Perubahan Judul
            </Button>
          )}
          <Button asChild variant="outline" size="sm">
            <Link href="/thesis/new">Ajukan Judul Baru</Link>
          </Button>
        </div>
      </div>

      <Card>
        <CardHeader className="flex-row items-start justify-between space-y-0">
          <div className="space-y-1.5">
            <CardTitle className="text-xl leading-snug">{thesis.title}</CardTitle>
            <Badge variant={statusVariant(thesis.status)}>{thesis.status.replace(/_/g, ' ')}</Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {thesis.abstract && (
            <div>
              <p className="mb-1 text-sm font-medium text-muted-foreground">Abstrak</p>
              <p className="text-sm leading-relaxed">{thesis.abstract}</p>
            </div>
          )}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div>
              <p className="text-sm font-medium text-muted-foreground">Bidang Keahlian</p>
              <p className="text-sm">{thesis.field_of_study ?? '—'}</p>
            </div>
            <div>
              <p className="text-sm font-medium text-muted-foreground">Pembimbing</p>
              <p className="text-sm">
                {thesis.supervisors?.length ? thesis.supervisors.map((s) => s.full_name).join(', ') : 'Belum ditentukan'}
              </p>
            </div>
          </div>
          {thesis.kaprodi_notes && (
            <div className="rounded-lg border border-secondary/30 bg-secondary-50 p-4">
              <p className="text-sm font-medium text-secondary-foreground">Catatan Kaprodi</p>
              <p className="mt-1 text-sm">{thesis.kaprodi_notes}</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ── Riwayat Perubahan Judul ─────────────────────────────────────── */}
      <Card>
        <CardHeader className="flex-row items-center justify-between space-y-0">
          <div className="space-y-1">
            <CardTitle className="flex items-center gap-2 text-base">
              <History className="h-4 w-4 text-primary" /> Riwayat Perubahan Judul
            </CardTitle>
            <CardDescription>Pengajuan dan hasil review perubahan judul skripsi Anda</CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          {requests.isLoading ? (
            <Spinner className="py-8" />
          ) : changeRequests.length === 0 ? (
            <p className="py-6 text-center text-sm text-muted-foreground">Belum ada pengajuan perubahan judul.</p>
          ) : (
            <div className="space-y-3">
              {changeRequests.map((r) => (
                <div key={r.id} className="rounded-xl border border-border p-4">
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <p className="font-medium">Judul baru: {r.requested_title}</p>
                        {titleChangeBadge(r.status)}
                      </div>
                      <p className="mt-1 text-xs text-muted-foreground">
                        Diajukan {formatDate(r.created_at)}
                        {r.requested_by?.full_name && ` oleh ${r.requested_by.full_name}`}
                      </p>
                    </div>
                    {r.status === 'PENDING' && (
                      <Button size="sm" variant="ghost" className="text-danger-700 hover:bg-danger/10" onClick={() => setCancelTarget(r)}>
                        <XCircle className="h-3.5 w-3.5" /> Batalkan
                      </Button>
                    )}
                  </div>
                  <div className="mt-3 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
                    <div className="rounded-lg bg-muted/50 p-3">
                      <p className="text-xs font-medium text-muted-foreground">Judul Sebelumnya</p>
                      <p className="mt-0.5 leading-snug line-through decoration-muted-foreground/40">{r.previous_title}</p>
                    </div>
                    <div className="rounded-lg bg-primary-50 p-3">
                      <p className="text-xs font-medium text-primary-700">Judul yang Diajukan</p>
                      <p className="mt-0.5 leading-snug">{r.requested_title}</p>
                    </div>
                  </div>
                  {r.reason && (
                    <p className="mt-3 text-sm">
                      <span className="font-medium text-muted-foreground">Alasan: </span>
                      {r.reason}
                    </p>
                  )}
                  {(r.reviewed_by?.full_name || r.review_notes) && (
                    <div className="mt-3 border-t border-border pt-3 text-sm">
                      {r.reviewed_by?.full_name && (
                        <p className="text-muted-foreground">
                          <span className="font-medium text-foreground">Direview oleh:</span> {r.reviewed_by.full_name}
                        </p>
                      )}
                      {r.review_notes && (
                        <p className="mt-1 text-muted-foreground">
                          <span className="font-medium text-foreground">Catatan Pembimbing:</span> {r.review_notes}
                        </p>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* ── Dialog: Ajukan Perubahan Judul ─────────────────────────────── */}
      <Dialog
        open={submitOpen}
        onClose={() => setSubmitOpen(false)}
        title="Ajukan Perubahan Judul"
        description="Perubahan judul akan diproses oleh Dosen Pembimbing Anda."
      >
        <form onSubmit={onSubmit} noValidate className="space-y-4">
          {actionError && <Alert variant="danger">{actionError}</Alert>}
          <div>
            <Label>Judul Saat Ini</Label>
            <Input value={thesis.title} readOnly className="bg-muted/60 text-muted-foreground" />
          </div>
          <div>
            <Label htmlFor="requested_title" required>Judul Baru</Label>
            <Textarea
              id="requested_title"
              rows={3}
              placeholder="Tulis judul baru skripsi Anda (minimal 10 kata)"
              invalid={!!errors.requested_title}
              {...register('requested_title')}
            />
            {errors.requested_title && <p className="mt-1 text-xs text-danger">{errors.requested_title.message}</p>}
          </div>
          <div>
            <Label htmlFor="reason">Alasan Perubahan</Label>
            <Textarea
              id="reason"
              rows={2}
              placeholder="Alasan mengajukan perubahan judul (opsional)"
              {...register('reason')}
            />
          </div>
          <div className="flex flex-wrap justify-end gap-2 pt-1">
            <Button type="button" variant="ghost" onClick={() => setSubmitOpen(false)}>Batal</Button>
            <Button type="submit" loading={submit.isPending}>
              <PencilLine className="h-4 w-4" /> Ajukan
            </Button>
          </div>
        </form>
      </Dialog>

      {/* ── Dialog: Batalkan Permintaan ────────────────────────────────── */}
      <Dialog
        open={Boolean(cancelTarget)}
        onClose={() => setCancelTarget(null)}
        title="Batalkan Permintaan Perubahan Judul?"
        description="Permintaan yang sedang diproses akan ditarik dan tidak dapat dikembalikan."
      >
        {cancelTarget && (
          <div className="space-y-4">
            <div className="rounded-lg bg-muted/50 p-3 text-sm">
              <p className="text-xs font-medium text-muted-foreground">Judul yang diajukan</p>
              <p className="mt-0.5">{cancelTarget.requested_title}</p>
            </div>
            {cancelReq.isError && <Alert variant="danger">{getErrorMessage(cancelReq.error)}</Alert>}
            <div className="flex flex-wrap justify-end gap-2">
              <Button type="button" variant="ghost" onClick={() => setCancelTarget(null)}>Kembali</Button>
              <Button
                type="button"
                variant="danger"
                loading={cancelReq.isPending}
                onClick={() => cancelReq.mutate(cancelTarget.id)}
              >
                Ya, Batalkan
              </Button>
            </div>
          </div>
        )}
      </Dialog>
    </div>
  )
}
