// frontend/src/components/features/landing/landing-button.tsx
import Link from 'next/link'
import type { ReactNode } from 'react'
import { cn } from '@/lib/utils/cn'

const baseClasses =
  'accent-ring inline-flex h-12 items-center justify-center gap-2 rounded-full px-7 text-sm font-medium transition'

type Variant = 'solid' | 'outline'

const variantClasses: Record<Variant, string> = {
  solid: 'bg-st-text text-st-bg hover:opacity-90',
  outline:
    'border border-st-stroke bg-st-surface text-st-text hover:border-(--st-accent-from)/40 hover:bg-st-surface-hi',
}

/**
 * LandingButton — the pill CTA shared by the hero and closing section.
 * Hash hrefs (in-page anchors) render as plain <a>; everything else uses
 * next/link so navigation stays client-side.
 */
export function LandingButton({
  href,
  variant = 'solid',
  className,
  children,
}: {
  href: string
  variant?: Variant
  className?: string
  children: ReactNode
}) {
  const classes = cn(baseClasses, variantClasses[variant], className)

  if (href.startsWith('#')) {
    return (
      <a href={href} className={classes}>
        {children}
      </a>
    )
  }

  return (
    <Link href={href} className={classes}>
      {children}
    </Link>
  )
}

// apps/web/src/lib/components/landing/LandingButton.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let {
    href,
    variant = "solid",
    class: className = "",
    children,
  }: {
    href: string;
    variant?: "solid" | "outline";
    class?: string;
    children: Snippet;
  } = $props();

  const cls =
    "accent-ring inline-flex h-12 items-center justify-center gap-2 rounded-full px-7 text-sm font-medium transition " +
    (variant === "solid"
      ? "bg-st-text text-st-bg hover:opacity-90"
      : "border border-st-stroke bg-st-surface text-st-text hover:border-(--st-accent-from)/40 hover:bg-st-surface-hi") +
    " " +
    className;
</script>

<a {href} class={cls}>{@render children()}</a>
